// Code generated by goctl. DO NOT EDIT.
// Source: captcha.proto

package captchaclient

import (
	"context"

	"github.com/yaoqiuzheng98/rpc-client/client/captcha/pb/captcha"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GenerateRequest  = captcha.GenerateRequest
	GenerateResponse = captcha.GenerateResponse
	Request          = captcha.Request
	Response         = captcha.Response
	VerifyRequest    = captcha.VerifyRequest
	VerifyResponse   = captcha.VerifyResponse

	Captcha interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
		Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	}

	defaultCaptcha struct {
		cli zrpc.Client
	}
)

func NewCaptcha(cli zrpc.Client) Captcha {
	return &defaultCaptcha{
		cli: cli,
	}
}

func (m *defaultCaptcha) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := captcha.NewCaptchaClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultCaptcha) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	client := captcha.NewCaptchaClient(m.cli.Conn())
	return client.Generate(ctx, in, opts...)
}

func (m *defaultCaptcha) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	client := captcha.NewCaptchaClient(m.cli.Conn())
	return client.Verify(ctx, in, opts...)
}
